### ISSUE TITLE
Integer division

### ISSUE THREAD

**Issue by narimiran** [andhrelja/adventofcode#1]
https://github.com/andhrelja/adventofcode/blob/9272e0bbec59be91e65fd8f94c4156199f5af65a/2019/day01/day01.py#L6

Hint: Python ima integer division operator `//` za ovakve stvari, pa ovu liniju mozes pisati kao: `yield mass // 3 - 2`

**Comment by andhrelja** [comment]
Noted, hvala za hint :)
